### ISSUE TITLE
[Docs] Add README for back-end

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#20]
After bonus episode, push README upstream to each back-end service, including integration tests instructions for those trying to run that locally.

**Tasks**

* **Catalog**
    - [x] Add Implementation
    - [x] Add high-level architecture
    - [x] Add Integrations
    - [x] Add Tech debt/decision making thoughts
* **Booking**
    - [x] Add Implementation
    - [x] Add high-level architecture
    - [x] Add Integrations
    - [x] Add Tech debt/decision making thoughts
* **Loyalty**
    - [x] Add Implementation
    - [x] Add high-level architecture
    - [x] Add Integrations
    - [x] Add Tech debt/decision making thoughts
* **Payment**
    - [x] Add Implementation
    - [x] Add high-level architecture
    - [x] Add Integrations
    - [x] Add Tech debt/decision making thoughts

**Comment by heitorlessa** [comment]
PR merged
