### ISSUE TITLE
[CI] Enable tests

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#21]
Tests are not completely pushed upstream, and when they're finalized we need a new `ci` target to include deploy and tests altogether.

Given the major changes that are yet to be made in the last 4 episodes this is on hold.

**Comment by heitorlessa** [comment]
**Tasks**

* [ ] Automate Cognito User for E2E and retrieve them from Secrets Manager/SSM Parameter Store
* [ ] Add Integ tests to `make tests`
* [ ] Add Unit tests to `make tests`
* [ ] Add E2E tests to `make tests`
