### ISSUE TITLE
[Front-end] Booking: Remove hardcoded name in Booking Card

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#26]
When opening Booking details for more information the passenger name should be retrieved from Auth as all calls are dynamic, however we missed this in the booking episode.

### Tasks

* [x] Replace [static value for name attr to Profile name](https://github.com/aws-samples/aws-serverless-airline-booking/blob/3aa837c2d66ccddb4f8be58ec5f46df6163562f6/src/frontend/components/BookingFlight.vue#L9)
* [x] Use `mapState` to retrieve `profile` data
* [ ] Add placeholder if data isn't available

**Comment by heitorlessa** [comment]
Resolved by #27 27
